In [10]:
#Exp No:10

In [11]:
#aim:to perform simple regression

In [13]:
#Name:Vedant Dalvi
#Roll No:12
#Sec:C
#Subject:DSS
#Date:24/09/2026

In [4]:
import pandas as pd

In [5]:
import os

In [6]:
os.getcwd()

'C:\\Users\\HP'

In [7]:
os.chdir('C:\\Users\\HP')

In [8]:
data=pd.read_csv("C:\\Users\\HP\\OneDrive\\Desktop\\Salary.csv")

In [10]:
data.head()

   YearsExperience  Salary
0              1.1   39343
1              1.3   46205
2              1.5   37731
3              2.0   43525
4              2.2   39891

In [11]:
data.tail()

    YearsExperience  Salary
30             11.2  127345
31             11.5  126756
32             12.3  128765
33             12.9  135675
34             13.5  139465

In [12]:
data.describe()

       YearsExperience         Salary
count        35.000000      35.000000
mean          6.308571   83945.600000
std           3.618610   32162.673003
min           1.100000   37731.000000
25%           3.450000   57019.000000
50%           5.300000   81363.000000
75%           9.250000  113223.500000
max          13.500000  139465.000000

In [13]:
data.isna()

    YearsExperience  Salary
0             False   False
1             False   False
2             False   False
3             False   False
4             False   False
5             False   False
6             False   False
7             False   False
8             False   False
9             False   False
10            False   False
11            False   False
12            False   False
13            False   False
14            False   False
15            False   False
16            False   False
17            False   False
18            False   False
19            False   False
20            False   False
21            False   False
22            False   False
23            False   False
24            False   False
25            False   False
26            False   False
27            False   False
28            False   False
29            False   False
30            False   False
31            False   False
32            False   False
33            False   False
34            False   False

In [14]:
data.isna().sum()

YearsExperience    0
Salary             0
dtype: int64

In [15]:
data.columns

Index(['YearsExperience', 'Salary'], dtype='object')

In [16]:
data.shape

(35, 2)

In [17]:
data.size

70

In [18]:
data.ndim

2

#Independent and Dependent Varialbles

In [19]:
x=data.drop('Salary',axis=1)

In [20]:
x.head

<bound method NDFrame.head of     YearsExperience
0               1.1
1               1.3
2               1.5
3               2.0
4               2.2
5               2.9
6               3.0
7               3.2
8               3.2
9               3.7
10              3.9
11              4.0
12              4.0
13              4.1
14              4.5
15              4.9
16              5.1
17              5.3
18              5.9
19              6.0
20              6.8
21              7.1
22              7.9
23              8.2
24              8.7
25              9.0
26              9.5
27              9.6
28             10.3
29             10.5
30             11.2
31             11.5
32             12.3
33             12.9
34             13.5>

In [21]:
y=data.Salary

In [22]:
y=data.drop('Salary',axis=1)

In [23]:
y.head

<bound method NDFrame.head of     YearsExperience
0               1.1
1               1.3
2               1.5
3               2.0
4               2.2
5               2.9
6               3.0
7               3.2
8               3.2
9               3.7
10              3.9
11              4.0
12              4.0
13              4.1
14              4.5
15              4.9
16              5.1
17              5.3
18              5.9
19              6.0
20              6.8
21              7.1
22              7.9
23              8.2
24              8.7
25              9.0
26              9.5
27              9.6
28             10.3
29             10.5
30             11.2
31             11.5
32             12.3
33             12.9
34             13.5>

In [24]:
from sklearn.model_selection import train_test_split

In [25]:
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=0,test_size=0.30)

In [26]:
print(x_train.shape)

(24, 1)

In [27]:
x_test.shape

(11, 1)

# MODEL FITTING

In [28]:
from sklearn.linear_model import LinearRegression
LR=LinearRegression()
LR.fit(x_train,y_train)

LinearRegression()

In [29]:
#Assigning Coefficient (slope) to m
m = LR.coef_

In [30]:
print("Coefficient  :" , m)

Coefficient  : [[1.]]

In [31]:
#Assigning Y-intercept to a
c = LR.intercept_

In [32]:
print("Intercept : ", c)

Intercept :  [1.77635684e-15]

# Y=MX+C

# PREDICTION

In [33]:
y_pred=LR.predict(x_test)

In [34]:
y_pred

array([[10.5],
       [ 6.8],
       [ 5.1],
       [10.3],
       [ 7.9],
       [ 4.9],
       [ 3.9],
       [ 1.5],
       [ 4. ],
       [ 9.6],
       [ 9. ]])

# Evaluation Metrics

In [36]:
from sklearn import metrics

Accuracy

In [38]:
Accuracy = LR.score(x_test, y_test)
Accuracy

1.0

MAE

In [39]:
print(metrics.mean_absolute_error(y_test,y_pred))

4.440892098500626e-16

MSE

In [41]:
import numpy as np

In [42]:
print(np.sqrt(metrics.mean_squared_error(y_test,y_pred)))

6.694896738718451e-16

RMSE

In [43]:
rmse = np.sqrt(metrics.mean_squared_error(y_test,y_pred))
print("RMSE:", rmse)

RMSE: 6.694896738718451e-16